### ISSUE TITLE
needs better website

### ISSUE THREAD

**Issue by createandbuild** [jeffreyzpan/hacknehs#4]
The website hacknehs.org doesn't seem to be updated AT ALL. Where is the website manage??? Where is Oreo???

**Comment by jeffreyzpan** [comment]
Indeed this seems to be an important issue. However, this is not an issue with the pip package; rather this appears to be an issue with [the hacknehs website itself](https://github.com/hackNEHS/hacknehs-2020). Quite unfortunate I must say.
